auth:
    admin_password_hash: $2a$10$5GHGEyGqEU8FIyV5IGcDP.hJEfnW08k7VlfjVmo96Zo7.t1nx80je
    admin_username: admin
    jwt_secret: eadaa9c704c7ab0ff6e8d8b5509cbe390a25f650b9fe025fbc87522949cec526
    jwt_ttl: 12h
data_dir: ./data
instances_dir: ./data/instances
log_level: info
plugins_dir: ./data/plugins
server:
    listen: :8080
